# Generated by Django 2.1.4 on 2019-02-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aff_site', '0007_auto_20190203_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
