# Generated by Django 2.1.4 on 2019-02-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aff_site', '0008_auto_20190203_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
