# Generated by Django 2.1.4 on 2019-02-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aff_site', '0009_auto_20190203_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='city',
            field=models.CharField(default='City', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='country',
            field=models.CharField(default='Country', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='postal_code',
            field=models.CharField(default='00000', max_length=10),
            preserve_default=False,
        ),
    ]
