# Generated by Django 2.1.4 on 2019-02-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aff_site', '0010_auto_20190203_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
